import type { SourcedProductRecord } from '@atelier/domain';

export const sampleStagedProducts: SourcedProductRecord[] = [
  {
    id: 'sp-1',
    source: {
      sourcePlatform: 'amazon',
      sourceIdentifier: 'ASIN123',
      ingestMethod: 'fixture_seed',
      canonicalUrl: 'https://www.amazon.com/dp/ASIN123',
      affiliateUrl: 'https://www.amazon.com/dp/ASIN123?tag=palletelle-20',
      retrievedAt: '2026-04-18T00:00:00Z',
      sourceFieldMap: {
        title: 'raw.title',
        category: 'raw.category',
        priceText: 'raw.price',
        availabilityText: 'raw.availability',
      },
      rawSnapshot: {
        title: 'Soft Linen Shirt on Amazon',
        category: 'Men\'s Linen Shirts',
        price: '$148',
        availability: 'In stock',
      },
    },
    normalized: {
      title: 'Soft Linen Shirt',
      brand: 'Amazon Example',
      category: 'Shirt',
      sourceColor: 'Warm ivory',
      material: '100% linen',
      priceText: '$148',
      availabilityText: 'In stock',
    },
    inferred: {
      paletteFamily: 'warm-neutral',
      colorHarmony: 'soft olive compatible',
      styleDirection: 'relaxed polished',
      styleOpinion: 'A calm neutral anchor',
    },
    provenance: {
      normalizedAt: '2026-04-18T00:05:00Z',
      reviewedAt: undefined,
      reviewedBy: undefined,
      dataConfidence: 'medium',
      confidenceReason: 'Explicit source fields are present, but compatibility remains heuristic.',
      confidenceImprovement: 'Refresh source fields and enrich supporting product attributes.',
      missingAttributes: ['validated fit notes'],
      uncertainAttributes: ['cross-item harmony strength'],
    },
    freshness: {
      priceFreshness: {
        status: 'fresh',
        checkedAt: '2026-04-18T00:10:00Z',
        thresholdHours: 24,
        reason: 'recent source retrieval',
      },
      availabilityFreshness: {
        status: 'fresh',
        checkedAt: '2026-04-18T00:10:00Z',
        thresholdHours: 12,
        reason: 'recent source retrieval',
      },
      lastCheckedAt: '2026-04-18T00:10:00Z',
    },
    visibility: {
      isPublic: false,
      intendedActive: false,
      visibilityNotes: 'Fixture review record.',
    },
    stagingStatus: 'needs_review',
  },
  {
    id: 'sp-2',
    source: {
      sourcePlatform: 'amazon',
      sourceIdentifier: 'ASIN999',
      ingestMethod: 'fixture_seed',
      canonicalUrl: 'https://www.amazon.com/dp/ASIN999',
      affiliateUrl: 'https://www.amazon.com/dp/ASIN999?tag=palletelle-20',
      retrievedAt: '2026-04-16T00:00:00Z',
      sourceFieldMap: {
        title: 'raw.title',
        priceText: 'raw.price',
      },
      rawSnapshot: {
        title: 'Rosewood Knit Layer on Amazon',
        price: '$168',
        availability: 'Unknown',
      },
    },
    normalized: {
      title: 'Rosewood Knit Layer',
      brand: 'Amazon Example',
      category: 'Knit layer',
      sourceColor: 'Muted rosewood',
      material: 'Wool blend',
      priceText: '$168',
      availabilityText: 'Unknown',
    },
    inferred: {
      paletteFamily: 'muted-warm',
      colorHarmony: 'warm ivory possible',
      styleDirection: 'soft layered warmth',
      styleOpinion: 'Tentative warm accent piece',
    },
    provenance: {
      normalizedAt: '2026-04-16T00:05:00Z',
      reviewedAt: undefined,
      reviewedBy: undefined,
      dataConfidence: 'low',
      confidenceReason: 'Key source fields are stale and recommendation strength is weak.',
      confidenceImprovement: 'Refresh source data and verify stronger compatibility support.',
      missingAttributes: ['recent availability confirmation'],
      uncertainAttributes: ['critical'],
    },
    freshness: {
      priceFreshness: {
        status: 'stale',
        checkedAt: '2026-04-16T00:10:00Z',
        thresholdHours: 24,
        reason: 'price older than allowed freshness window',
      },
      availabilityFreshness: {
        status: 'stale',
        checkedAt: '2026-04-16T00:10:00Z',
        thresholdHours: 12,
        reason: 'availability older than allowed freshness window',
      },
      lastCheckedAt: '2026-04-16T00:10:00Z',
    },
    visibility: {
      isPublic: false,
      intendedActive: false,
      visibilityNotes: 'Fixture review record.',
    },
    stagingStatus: 'stale',
  },
];
